config/routes.rb
Rails.application.routes.draw do
  resources 'customers'
  get 'welcome/index'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:edit, :update, :show, :destroy]
  def index
    @customers = Customer.all
  end
  def show

  end
  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to customers_path, notice: "Cliente criado com sucesso!"
    else
      render :new
    end
  end

  def update
    if @customer.update(customer_params)
      redirect_to customers_path(@customer), notice: "Cliente atualizado com sucesso"
    else
      render :edit
    end
  end

  def edit
  end
  def destroy
    if @customer.destroy
      redirect_to customers_path, notice: "Cliente excluido com sucesso"
    else
      render :index
    end
  end

  private

  def set_customer
    @customer = Customer.find_by_id(params[:id])
  end
  def customer_params
    params.require(:customer).permit(:id, :name, :email, :phone, :avatar, :smoker)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/create.html.erb
<h1>Customers#create</h1>
<p>Find me in app/views/customers/create.html.erb</p>

app/views/customers/delete.html.erb
<h1>Customers#delete</h1>
<p>Find me in app/views/customers/delete.html.erb</p>

app/views/customers/edit.html.erb
<% if @customer.errors.any? %>
  <ul>
    <% @customer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>Editar cliente</h1>
<%= form_for @customer,  data: { turbo: false }  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :avatar %>
  <%= f.file_field :avatar %>

  <%= f.radio_button :smoker, 'S' %>
  <%= f.label :smoke, 'Sim' %>
  <%= f.radio_button :smoker, 'N' %>
  <%= f.label :smoker, 'Não' %>
  <%= f.submit "Atualizar" %>
<% end %>

app/views/customers/index.html.erb
<% if flash[:notice] %>
 <p> <%= flash[:notice] %> </p>
<% end %>
<h1>Lista de clientes</h1>

<% @customers.each do |customer| %>
  <p>Name: <%= customer[:name] %></p>
  <p>Email: <%= customer[:email] %></p>
  <p>Phone: <%= customer[:phone] %></p>
  <%= link_to "Excluir", customer, method: :delete %>
<% end %>
<%= link_to "Novo cliente", new_customer_path %>

app/views/customers/new.html.erb
<% if @customer.errors.any? %>
  <ul>
    <% @customer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h1>Novo cliente</h1>
<%= form_for @customer,  data: { turbo: false }  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :avatar %>
  <%= f.file_field :avatar %>

  <%= f.radio_button :smoker, 'S' %>
  <%= f.label :smoke, 'Sim' %>
  <%= f.radio_button :smoker, 'N' %>
  <%= f.label :smoker, 'Não' %>
  <%= f.submit "criar" %>
<% end %>

app/views/customers/show.html.erb
<strong>Nome: </strong>
<p><%= @customer.name %></p>

<strong>Email: </strong>
<p><%= @customer.email %></p>

<strong>Telefone: </strong>
<p><%= @customer.phone %></p>

app/views/customers/update.html.erb
<h1>Customers#update</h1>
<p>Find me in app/views/customers/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tdd</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to tdd RoR app</h1>

<ul>
  <li><%= link_to "Cadastro de clientes", customers_path %></li>
</ul>